- BT Advanced Clan Mechs/chassis/chassisdef_shadowhawk_SHD_C.json
melee rebalance for the clan refit shadowhawk
> shad melee'd

- BT Advanced Clan Tanks/vehicle/vehicledef_PIKE_CLAN.json
> tank manifest entry fix

- BT Advanced Clan Mechs/mech/mechdef_bloodasp_A.json
removed the extra c dhs and added armor to make the variant drop legal
> to much in the RT

- BT Advanced Clan Gear/weapons/Weapon_LRM_ATM12_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_LRM_ATM3_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_LRM_ATM6_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_LRM_ATM9_CLAN.json
- BT Advanced Clan Mechs/mech/mechdef_bloodasp_A.json
- Heavy Metal Unit Module/chassis/chassisdef_rifleman_RFL_C.json
> Dev-rifleman melee'd

- BT Advanced Clan Gear/weapons/Weapon_PPC_PPCER_CLAN.json
- BT Advanced Events/events_Clans/wulf_event_co_spotlightFace.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_Addasar.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_Balawat.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_Brixtana.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_CatesHold.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_DainmarMajoris.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_Dunianshire.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_EarlyDawn.json
- InnerSphereMap/StreamingAssets/data/starsystem/starsystemdef_NewAbilene.json
Added for compatibility
"planet_faction_magistracyofcanopus" 
to vanilla planets that only use 
"planet_faction_magistracy"
> Vanilla Planet Tags Appended

- BT Advanced Core/mod.json
updated core version number same as master
> updated mod,json to 5.1

- BT Advanced Core/mod.json
- BT Advanced Starters/BTA_Starters_Base/Starter_BTA_diff_Clan.json
clever girl from being required and added abilities to manifest, it was missing
> Dev just an update

- BT Advanced Clan Mechs/chassis/chassisdef_marauder_MAD_C.json
> Marauder melee'd

- InnerSphereMap/StarSystems/starsystemdef_Zhaomaon(CluffsStand3130+).json
- Urban Warfare Flashpoints/flashpoints/fp_tournament.json
fixed a comma for zhaomaon as well as overrode the fp to go to that planet
> fixes for the Tournament fp

- BT Advanced Events/events_Clans/tbone_event_co_byeOptio.json
- BT Advanced Events/events_Clans/tbone_event_co_honorVirago.json
- BT Advanced Events/events_Clans/tbone_event_co_spotlightOptio.json
- BT Advanced Events/events_Clans/tbone_event_co_spotlightVirago.json
Events for Optio the Spy
Events for Virago the Clanner
> New Events

- BT Advanced Clan Mechs/chassis/chassisdef_victor_VTR_C.json
- InnerSphereMap/settings.json
> Victor melee'd

- BT Advanced Clan Mechs/mech/mechdef_direwolf_DW-PRIME.json
- BT Advanced Clan Mechs/mech/mechdef_ebonjaguar_PRIME.json
fixes for dw and ebon jacg primes
> mech fixes

- BT Advanced Clan Mechs/chassis/chassisdef_highlanderiic_HGN-IIC-4.json
- BT Advanced Clan Mechs/chassis/chassisdef_mauler_MAL-5C.json
> HGN-IIC-4 actuator limit

- BT Advanced Clan Mechs/chassis/chassisdef_atlas_AS7_C.json
Atlas melee rebalance, inculded as it had the same numbers as the IS variants
> Atlas melee'd

- BT Advanced Contracts/contract/ambushconvoy/8/AmbushConvoy_ClanGrudge_ConvoyInterceptCGB.json
- BT Advanced Contracts/contract/ambushconvoy/8/AmbushConvoy_ClanGrudge_ConvoyInterceptCJF.json
- BT Advanced Contracts/contract/ambushconvoy/8/AmbushConvoy_ClanGrudge_ConvoyInterceptCWF.json
- BT Advanced Contracts/contract/destroybase/8/DestroyBase_ClanGrudge_DestroyFacilityCGB.json
- BT Advanced Contracts/contract/destroybase/8/DestroyBase_ClanGrudge_DestroyFacilityCJF.json
- BT Advanced Contracts/contract/destroybase/8/DestroyBase_ClanGrudge_DestroyFacilityCWF.json
- BT Advanced Contracts/contract/simplebattle/8/SimpleBattle_ClanGrudge_TakeTheBaitCGB.json
- BT Advanced Contracts/contract/simplebattle/8/SimpleBattle_ClanGrudge_TakeTheBaitCJF.json
- BT Advanced Contracts/contract/simplebattle/8/SimpleBattle_ClanGrudge_TakeTheBaitCWF.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cgb_base.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cgb_convoy.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cgb_fight.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cjf_base.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cjf_convoy.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cjf_fight.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cwf_base.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cwf_convoy.json
- BT Advanced Contracts/events_Clans/tbone_event_co_clanraid_cwf_fight.json
add Clan rep earning event/contracts
> add clans events

- BT Advanced Core/mod.json
> core version number bump

- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC10_LBX_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC20_LBX_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC2_LBX_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC5_LBX_CLAN.json
> Clan LBX sound fix

- BT Advanced Clan Mechs/chassis/chassisdef_NovaCat_NCT-A.json
- BT Advanced Clan Mechs/chassis/chassisdef_NovaCat_NCT-B.json
- BT Advanced Clan Mechs/chassis/chassisdef_NovaCat_NCT-C.json
- BT Advanced Clan Mechs/chassis/chassisdef_NovaCat_NCT-D.json
- BT Advanced Clan Mechs/chassis/chassisdef_NovaCat_NCT-Prime.json
- BT Advanced Clan Mechs/mech/mechdef_NovaCat_NCT-A.json
- BT Advanced Clan Mechs/mech/mechdef_NovaCat_NCT-B.json
- BT Advanced Clan Mechs/mech/mechdef_NovaCat_NCT-C.json
- BT Advanced Clan Mechs/mech/mechdef_NovaCat_NCT-D.json
- BT Advanced Clan Mechs/mech/mechdef_NovaCat_NCT-Prime.json
> nova cats have fixed armor

- BT Advanced Clan Mechs/chassis/chassisdef_hellbringer_HBR-A.json
- BT Advanced Clan Mechs/chassis/chassisdef_hellbringer_HBR-B.json
- BT Advanced Clan Mechs/chassis/chassisdef_hellbringer_HBR-C.json
- BT Advanced Clan Mechs/chassis/chassisdef_hellbringer_HBR-F.json
- BT Advanced Clan Mechs/chassis/chassisdef_hellbringer_HBR-H.json
- BT Advanced Clan Mechs/chassis/chassisdef_hellbringer_HBR-P.json
- BT Advanced Clan Mechs/chassis/chassisdef_hellbringer_HBR-Prime.json
- BT Advanced Clan Mechs/mech/mechdef_hellbringer_HBR-A.json
- BT Advanced Clan Mechs/mech/mechdef_hellbringer_HBR-B.json
- BT Advanced Clan Mechs/mech/mechdef_hellbringer_HBR-C.json
- BT Advanced Clan Mechs/mech/mechdef_hellbringer_HBR-F.json
- BT Advanced Clan Mechs/mech/mechdef_hellbringer_HBR-H.json
- BT Advanced Clan Mechs/mech/mechdef_hellbringer_HBR-P.json
- BT Advanced Clan Mechs/mech/mechdef_hellbringer_HBR-Prime.json
> Hellbringers also have fixed armor

- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC10_LBX_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC20_LBX_CLAN.json
used another audio for the lbx 10 and 20
> quiter lbx

- BT Advanced Core/mod.json
> BetterJuggernaut got ate

- BT Advanced Clan Gear/engines/emod_engineslots_cxxl_center.json
but you can get a regular clan xl
> clan xxl not lootable

- BT Advanced Core/Faction.json
faction_Betrayers doesnt exist, change to point where it does in vanilla
> faction fix

- BT Advanced Clan Gear/internals/emod_structureslots_clanendorigged.json
> endorigged comma fix

- BT Advanced Clan Gear/internals/Gear_AP_CLAN.json
> parsing error fix

- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC10_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC20_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC2_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC5_CLAN.json
added "FireDelayMultiplier" to the base mode
> Clan UAC fire delay fix

- InnerSphereMap/StarSystems/starsystemdef_UnionofSamoyedicColonies.json
shouldnt break the system, should fix target contract generation for it
> star system comma fix

- BT Advanced Core/mod.json
> OptionallyDependsOn for FlashpointEnabler

- InnerSphereMap/Factions/faction_Circinus.json
- InnerSphereMap/Factions/faction_Delphi.json
- InnerSphereMap/Factions/faction_Hanse.json
- InnerSphereMap/Factions/faction_JarnFolk.json
- InnerSphereMap/Factions/faction_Marian.json
- InnerSphereMap/Factions/faction_RimCollection.json
- InnerSphereMap/StreamingAssets/data/factions/faction_AuriganRestoration.json
Locals added to enemies to get them as OpFor
> Locals to fight the Periphery

- BT Advanced Clan Mechs/mech/mechdef_adder_ADR-B.json
- BT Advanced Clan Mechs/mech/mechdef_firemoth_FM-A.json
- BT Advanced Clan Mechs/mech/mechdef_firemoth_FM-B.json
- BT Advanced Clan Mechs/mech/mechdef_firemoth_FM-C.json
- BT Advanced Clan Mechs/mech/mechdef_firemoth_FM-D.json
- BT Advanced Clan Mechs/mech/mechdef_firemoth_FM-E.json
- BT Advanced Clan Mechs/mech/mechdef_firemoth_FM-H.json
- BT Advanced Clan Mechs/mech/mechdef_firemoth_FM-PRIME.json
dropped 1t armor to make drop legal
> Adder ADR-B weight fix

- BT Advanced Core/mod.json
was missing DataAddendumEntries in core mod.json
> fixed weaponenum

- BT Advanced Clan Gear/internals/Gear_LifeSupportB_Negative_Clan_Quirks.json
> clan melee penalty updated in description

- BT Advanced Clan Mechs/mech/mechdef_linebacker_LBK-A.json
- BT Advanced Clan Mechs/mech/mechdef_linebacker_LBK-B.json
- BT Advanced Clan Mechs/mech/mechdef_linebacker_LBK-C.json
- BT Advanced Clan Mechs/mech/mechdef_linebacker_LBK-D.json
- BT Advanced Clan Mechs/mech/mechdef_linebacker_LBK-E.json
- BT Advanced Clan Mechs/mech/mechdef_linebacker_LBK-H.json
- BT Advanced Clan Mechs/mech/mechdef_linebacker_LBK-PRIME.json
is a heavy mech, so replaced unit_assault with unit_heavy
> linebacker tag fix

- BT Advanced Core/mod.json
> SizeMatters added as a requirement

- BT Advanced Events/events_Clans/wulf_event_co_TexTalks1.json
> some malformed json cleanup

- InnerSphereMap/StarSystems/starsystemdef_Arboris.json
- InnerSphereMap/StarSystems/starsystemdef_Ares.json
- InnerSphereMap/StarSystems/starsystemdef_Gei-Fu.json
- InnerSphereMap/StarSystems/starsystemdef_Geifer.json
- InnerSphereMap/StarSystems/starsystemdef_Hustaing.json
- InnerSphereMap/StarSystems/starsystemdef_Latice.json
- InnerSphereMap/StarSystems/starsystemdef_Lesalles.json
- InnerSphereMap/StarSystems/starsystemdef_Umgard_Flipped.json
> more json fixes

- BT Advanced Clan Gear/internals/Gear_Talons.json
- BT Advanced Clan Mechs/mech/mechdef_bane_BNE-1.json
- BT Advanced Clan Mechs/mech/mechdef_bane_BNE-2.json
- BT Advanced Clan Mechs/mech/mechdef_bane_BNE-3.json
- InnerSphereMap/StreamingAssets/data/factions/faction_SelfEmployed.json
dunno how this comma keeps coming back, file is a valid json again
> fix talons again

- BT Advanced Clan Gear/ammobox/Ammo_AmmunitionBox_Hyper_GAUSS.json
> updated to ammo cost to match bonus description

- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC10_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC20_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC2_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC5_CLAN.json
- BT Advanced Starters/BTA_itemCollection_Mechs/itemCollection_Mechs_Starting_Outworlds_Light.csv
> starting list fix

- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-A.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-B.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-C.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-D.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-E.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-H.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-PRIME.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-S.json
- BT Advanced Clan Mechs/chassis/chassisdef_timberwolf_TW-X.json
to fix affinity showing up as the rakshasa instead of timberwolf
> Timberwolf Assembly variant

- BT Advanced Clan Mechs/chassis/chassisdef_firefly_FFL-C.json
had medium mech max armor numbers
> firefly max armor fix

- DynamicShops/fshops/AllClans.json
- DynamicShops/fshops/Chainelane.json
- DynamicShops/fshops/Circinus.json
- DynamicShops/fshops/Comstar.json
- DynamicShops/fshops/Delphi.json
- DynamicShops/fshops/Hanse.json
- DynamicShops/fshops/JarnFolk.json
- DynamicShops/fshops/Marian.json
- DynamicShops/fshops/Outworld.json
- DynamicShops/fshops/Rasalhague.json
- DynamicShops/fshops/Rezak.json
> faction shop quick fix

- DynamicShops/fshops/Chainelane.json
- DynamicShops/fshops/Comstar.json
- DynamicShops/fshops/Delphi.json
- DynamicShops/fshops/Hanse.json
- DynamicShops/fshops/JarnFolk.json
- DynamicShops/fshops/Marian.json
- DynamicShops/fshops/Rezak.json
> copypasta fixes

- DynamicShops/sshops/comstar.json
- DynamicShops/sshops/marian.json
- DynamicShops/sshops/outworld.json
- DynamicShops/sshops/rasalhague.json
same change as main dev git, + added to standing
> ism sshops as well

- BT Advanced Core/mod.json
same ones added to Core's mod.json on main git
> updated incompatibilities

- BT Advanced Clan Mechs/mech/mechdef_kitfox_A.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_B.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_C.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_D.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_E.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_G.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_H.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_PRIME.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_S.json
- BT Advanced Clan Mechs/mech/mechdef_kitfox_W.json
searched for and removed more Isfixed from mechdefs
> IsFixed mechdef cleanup

- BT Advanced Clan Tanks/vehicle/vehicledef_APC_INDRA_CLAN.json
- BT Advanced Clan Tanks/vehicle/vehicledef_APC_MAXIM_CLAN.json
> clannovacat repme fix

- BT Advanced Clan Mechs/chassis/chassisdef_prometheus_PMTH-1.json
has same max armor as other non clan 75t mechs
> Prometheus armor fix

- BT Advanced Turrets/TurretChassis/turretchassisdef_lightlbx_C.json
> turret missing quotation fix

- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-A.json
- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-B.json
- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-DS.json
- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-H.json
- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-PRIME.json
- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-S.json
- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-W.json
- BT Advanced Clan Mechs/chassis/chassisdef_direwolf_DW-X.json
- BT Advanced Clan Tanks/vehicle/vehicledef_PUMA-2_CLAN.json
- BT Advanced Clan Tanks/vehicle/vehicledef_PUMA_CLAN.json
switch to AssemblyVariant so it shows up as DireWolf and not Direstar
> Dire Wolf affinity

- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC10_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC20_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC2_CLAN.json
- BT Advanced Clan Gear/weapons/Weapon_Autocannon_AC5_CLAN.json
> weapon jamming when they shouldnt fix

- DynamicShops/fshops/Delphi.json
> delphi faction store fix

- BT Advanced Clan Mechs/chassis/chassisdef_widowmaker_DW-BW.json
> windowmaker missing fields

- Community Content/mech/mechdef_madcatmkii_MCII-85.json
had Marauder name instead of Mad Cat MK II
> MCII-85 quick fix

- MissionControl/overrides/contracts/duoduel/DuoDuel_StarCrossedLovers.json
tracked down the source of this contract still spawning turrets that should be mechs
> fixed again this contract

- Community Content/mod.json
> ComContent comma fix

- BT Advanced Clan Mechs/mech/mechdef_firefly_FFL-C.json
> firefly tag fix

- BT Advanced Clan Tanks/vehicle/vehicledef_MORRIGU_CLAN.json
- BT Advanced Clan Tanks/vehicle/vehicledef_MORRIGU_LASER_CLAN.json
- BT Advanced Clan Tanks/vehiclechassis/vehiclechassisdef_MORRIGU_CLAN.json
- BT Advanced Clan Tanks/vehiclechassis/vehiclechassisdef_MORRIGU_LASER_CLAN.json
remove engine biome reference from details as with all other tanks
> Morrigu details edit

- BT Advanced Clan Mechs/mech/mechdef_arcticcheetah_A.json
- BT Advanced Clan Mechs/mech/mechdef_arcticcheetah_B.json
- BT Advanced Clan Mechs/mech/mechdef_arcticcheetah_C.json
- BT Advanced Clan Mechs/mech/mechdef_arcticcheetah_D.json
- BT Advanced Clan Mechs/mech/mechdef_arcticcheetah_H.json
- BT Advanced Clan Mechs/mech/mechdef_arcticcheetah_PRIME.json
Update tags for Arctic Cheetah to light from medium
> Update tags for Arctic Cheetah to light from medium
